package PhotovoltaicPanel;

import java.util.Random;

/**
 * This class contains information of one photovoltaic panel, could use to
 * calculate the power of that panel with given weather information
 * 
 * Resource: http://photovoltaic-software.com/PV-solar-energy-calculation.php
 * 
 * @author Luigi
 *
 */
public abstract class PhotovoltaicPanel {

	/** Cell length (in 1 m) */
	protected double cellL;

	/** Cell width (in 1 m) */
	protected double cellW;

	/** Number of cells per one PV panel */
	protected double nCells;

	/** Area of the PV panel (in 1 m^2) */
	protected double panelArea;

	/**
	 * Percentage of actual electric energy get from sun with the energy loss in
	 * transform solar energy to electric energy
	 */
	protected double efficiency;

	/** Maximum power of the PV panel (in 1 kW) */
	protected double maxPowerOutput;

	private double performanceRatio;

	/**
	 * The temperature at which the maximum power calculated (in 1 degree Celsius)
	 */
	protected double standardTemperature;
	
	/** The coefficient that decrease performance ratio when temperature differ from standard temperature (in 1/K) */
	protected double coefficientTemperature;

	protected Random random;

	/**
	 * Build a PV panel, randomly generate a performace ratio
	 */
	public PhotovoltaicPanel() {
		this.random = new Random();
		// range between 0.5 and 0.9, default value = 0.75
		this.performanceRatio = (0.9 - 0.5) * random.nextDouble() + 0.5;
	}

	/**
	 * Calculate the efficiency of PV panel at temperature
	 * @param temperature Temperature in 1 degree Celsius
	 * @return Efficiency
	 */
	private double coefficientAt(double temperature) {
		if (temperature >= standardTemperature)
			return efficiency;
		return Math.max(0, efficiency + coefficientTemperature * (standardTemperature - temperature));
	}

	/**
	 * Calculate the energy generated by PV panel for one hour
	 * 
	 * @param solarRadiation Solar radiation in 1 kW/m^2
	 * @return Energy in 1kWh
	 */
	public double output(double solarRadiation, double temperature) {
		// power in kW
		double power = panelArea * coefficientAt(temperature) / 100 * solarRadiation * performanceRatio;

		if (Double.isNaN(power)) {
			System.out.println("Error: power of PV panel is " + power);
			System.exit(0);
		}

		// energy in kWh
		return Math.min(power, maxPowerOutput) * 1;
	}

	/** @return The panel area of the PV panel */
	public double getPanelArea() {
		return this.panelArea;
	}

	/** @return The name of the PV panel */
	public abstract String info();
}
